### ISSUE TITLE
AI hits don't update with mid-level difficulty changes.

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/rd#1]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

oliverabola@gmail.com, FlameDance#9223 (won't accept DMs)

### Summary

If you change the difficulty of the game during a level or in the "press the space bar to begin." screen in a level with ai notes, the ai hit bars will be sized differently from the player hit bars (see attachment)
![image](https://user-images.githubusercontent.com/100527514/180847934-cf6c57ea-ff11-4ff9-8ea8-564a90ee0999.png)

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 11

### Platform

Steam

### Device Info

PC

### Steps to Reproduce

1. Enter a level that contains ai notes, such as 3-3
2. Change the difficulty of the game
3. Begin the level

### Expected Behavior

The width of the ai hit bars would change to match the player hit bars.

### Observed Behavior

The width of the ai hit bars would be set based on what difficulty you entered the level with.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/rd/files/9183978/Player.log)

**Comment by RandomGuyJCI** [comment]
Fixed!
