### ISSUE TITLE
cls preview music change speed when selecting ice/hot speed

### ISSUE THREAD

**Issue by KirbyCreep** [7thbeatgames/rd#10]
### Please Check

- [x] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

sometimes you can't truly feel how slow/fast a song will be when the preview music stays at the same speed

### Suggestion / Solution

change the speed on the fly when selecting speed options

### Alternatives & Workarounds

well i mean it's more qol than a problem that needs to be fixed

### Demo & Mockup

it's audio based...

### Note

i suggested this before but i guess there's no harm in suggesting it again

**Comment by saladplainzone** [comment]
made a video mockup because i like this suggestion lol

https://user-images.githubusercontent.com/31338325/181748688-ed7979fa-255e-49d7-86ff-7c36444f8f25.mp4

**Comment by RandomGuyJCI** [comment]
Similarly, I think this should also be done for story mode levels.

**Comment by saladplainzone** [comment]
> Similarly, I think this should also be done for story mode levels.

story mode levels don't have a music preview though? unless you mean just the level select background music in general but i feel like that'd be a bit janky

**Comment by saladplainzone** [comment]
story mode levels don't have a music preview though? unless you mean just the level select background music in general but i feel like that'd be a bit janky

**Comment by RandomGuyJCI** [comment]
I may be stupid

Yeah I forgot about that h

**Comment by RandomGuyJCI** [comment]
Implemented in dev!
