### ISSUE TITLE
Downloading a custom level from a Discord attachment URL appends ", attachment" to folder name

### ISSUE THREAD

**Issue by RandomGuyJCI** [7thbeatgames/rd#13]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Random Guy JCI#7029

### Summary

Recently I noticed that importing any level from a Discord attachment URL adds a ", attachment" to the end of the downloaded folder name. This has unintended side effects:

- You can download multiple of the same level from the same URL despite it not being usually allowed.
- Showing the level folder, either from the CLS or editor menu opens the This PC or Documents folder instead of the actual level folder.

This doesn't happen for non-discord URLs.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

Asus X560UD

### Steps to Reproduce

1. Open the CLS
2. Import any rdzip URL from Discord
3. Try importing the same URL again 

### Expected Behavior

The CLS should display a "Level already installed" error.

### Observed Behavior

The level installs again, and a duplicate level can be found in the CLS.

### Reproduction Rate

100%

### Anything else?

So far I have not been able to find the root cause of the bug. It somehow seems to affect old versions of RD, even though it didn't happen previously?

**Comment by KirbyCreep** [comment]
well if it affects previous versions of rd, it could be discord messing something up?

**Comment by huantianad** [comment]
It is in fact, discord messing something up. I am on the edge of absolute self-destruction right now.

Let's go ahead and take a look at what headers discord is sending along with their attachemnts, specifically the `Content-Disposition` header which tells us what the filename of the file we're downloading is:
```bash
> curl -I "https://cdn.discordapp.com/attachments/611380148431749151/826102144716767232/Jazz_Emu_-_My_Brothe_An_Email_Funk_Opera.rdzip" | grep -Fi "content-disposition"
content-disposition: attachment;%20filename=Jazz_Emu_-_My_Brothe_An_Email_Funk_Opera.rdzip, attachment
```
Let's also take a look at an example from [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition):
```
Content-Disposition: attachment; filename="filename.jpg"
```
There's a few things wrong with what discord is sending to us, specifically that weird encoded space (the `%20`), lack of `"` around the filename (optional but would be nice), and most importantly, the random addition of `, attachment` to the end of the header. Why Discord, why.

Other people have had this problem too, and there's a [janky solution](https://www.reddit.com/r/discordapp/comments/w36gkh/comment/ikkreo7/?utm_source=share&utm_medium=web2x&context=3), apparently. Haven't tested if this somehow works with RD.

Not sure what to do here, we could make our header parsing more robust so it gives an error, or just add in this random edge case? Maybe we should just wait for discord to fix it?

**Comment by huantianad** [comment]
Fixed in dev!
