### ISSUE TITLE
Using different speeds in the editor by holding Shift or Ctrl switches the selected mode in the CLS when editing an installed level

### ISSUE THREAD

**Issue by Tiago1257** [7thbeatgames/rd#14]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

1257Plays#5105

### Summary

When using chili or ice speed in the editor while in an installed level, the speed you choose in the editor affects the levels in the Custom Level Select menu

https://user-images.githubusercontent.com/84469804/181864460-b1bf20e4-ad86-4bdf-89be-ef335fa8c417.mp4

### Version

v0.11.6 (r26) (steam beta)

### Operating System (OS)

Windows 11

### Platform

Steam

### Steps to Reproduce

1. Open the Custom Level Library
2. Select any level
3. Select "Edit level"
4. When it finishes loading, scrub while holding "Shift" or "Ctrl"
5. Pause the level and exit the editor without scrubbing again
The level speed should be the one you used in the editor

### Expected Behavior

I expected the game to go back to the Custom Level Library with the regular speed, as that is the one most people play on. Many times after doing this I play a level and the speed is different without me noticing.

### Observed Behavior

The level speed is switched to the one used in the editor and can be confused with regular speed if the player doesn't notice, causing them to accidentally enter a level in a different mode.

### Reproduction Rate

100%

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
