### ISSUE TITLE
Advanced Floating Text Action Visual Error

### ISSUE THREAD

**Issue by Jgouken** [7thbeatgames/rd#15]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Jgouken#4861

### Summary

The "Advaned Floating Text" action shows extra and overlapping text.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. In the Editor, create a "Floating Text" action.
2. Type in a string that would need the use of "Advanced Text actions" and create an Advanced Text action.
3. Select the Advanced Text action.

### Expected Behavior

Only the upper text should be shown.

### Observed Behavior

The "Advaned Floating Text" action shows extra and overlapping text, including an input box that contains "-1" 'beats'. 

### Reproduction Rate

100%

### Anything else?

![image](https://user-images.githubusercontent.com/65487563/181865999-38c3454f-3552-44e2-8c14-8d9ddcffba9e.png)

**Comment by huantianad** [comment]
Should be fixed in-dev but not sure on what this should be called. Maybe we could use the same text as in normal floating text? @giacomopc thoughts?

**Comment by authop** [comment]
@huantianad If you think it's resolved already, please close this issue. Thanks!
