### ISSUE TITLE
Samurai Techno has incorrect rank margins

### ISSUE THREAD

**Issue by RandomGuyJCI** [7thbeatgames/rd#16]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Random Guy JCI#7029

### Summary

It was recently discovered that the rank margins of the current version of Samurai Techno was different from the original release. Full explanation in the Anything Else section.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Play Samurai Techno in Story Mode
2. Get between 20-25 misses

### Expected Behavior

You'd get a D rank.

### Observed Behavior

You get an F rank instead.

### Reproduction Rate

100%

### Anything else?

After some investigation, I found out that the mar2021 release uses the hardcoded version of Samurai Techno. However, at some point, most of the hardcoded Story Mode levels were replaced with custom level versions. Although the level _does_ get initialized with the correct rank margins, they get overwritten by the default rank margins of custom levels.

![image](https://user-images.githubusercontent.com/22722393/182021639-4fcf81a7-61fd-4430-b673-c569f6969f29.png)

**Comment by giacomopc** [comment]
Fixed, thanks!
