### ISSUE TITLE
Unclickable part in editor

### ISSUE THREAD

**Issue by HellUser0** [7thbeatgames/rd#18]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

MyseIf#5880

### Summary

With Fullscreen off, a portion of the editor on the right becomes unclickable.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 7

### Platform

Steam

### Steps to Reproduce

1. Turn off fullscreen
2. Go to the editor

### Expected Behavior

The editor works as normal

### Observed Behavior

Some buttons (screenshot, snapping, etc.) becomes unusable

### Reproduction Rate

100%

### Anything else?

https://discord.com/channels/296802696243970049/304720987319173121/1000592229208961144

**Comment by DPS2004** [comment]
I have a similar issue, but with a smaller region than HellUser0.
![image](https://user-images.githubusercontent.com/10176105/182210147-5181aeb3-c16f-4d2c-8ff8-64638ee49f3b.png)

**Comment by Satellite-7th-Beat-Games** [comment]
Potential clue: DDRKirby(ISQ) mentioned a similar bug in [her devlog](https://ddrkirbyisq.medium.com/rhythm-quest-devlog-41-more-demo-polish-8359d5eb1ddb).

> Had to downgrade Unity because newer versions inexplicably drop mouse input near the upper-right corner of the window =/

**Comment by huantianad** [comment]
There has been a new update recently (2022.3.7) so we can check if that has any fixes as well

**Comment by RandomGuyJCI** [comment]
This issue has since been resolved, closing
