### ISSUE TITLE
Change the window movement to "One Screen" the first time OBS is detected to be running at the same time as RD.

### ISSUE THREAD

**Issue by purplpasta** [7thbeatgames/rd#19]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Pretty much every youtuber or live streamer who plays RD will have to fumble around with the window movement settings the first time they reach 2-X. This interrupts the flow of the game and can be annoying to find.

### Suggestion / Solution

The first time RD detects OBS being open at the same time as RD itself, it will automatically change the window dance settings to One Screen (only if window dance has not been activated before). The player can always change it back later and it won't be annoying for recording if 2-X has already been played.

**Comment by ColdlordXRepositories** [comment]
Maybe it should just be set to one screen for the first time, even if OBS isn’t running

**Comment by RandomGuyJCI** [comment]
Implemented in dev!
