### ISSUE TITLE
Change pause menu option after selecting it

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/rd#2]
### Is there an existing issue for this?

- [x] I searched for the issues, and made sure there were no duplicates.

### Contact Information

oliverabola@gmail.com, FlameDance#9223 (won't accept DMs)

### Summary

In pause menus, you can change which item you have highlighted after choosing an item.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 11

### Platform

Steam

### Device Info

PC

### Steps to Reproduce

1. Enter any pause menu (not the main menu)
2. Press any key that can select menu options
3. Within a tight timing window (around the second beep played when choosing a menu option), press up or down on the arrow keys

### Expected Behavior

The arrow key press would be ignored

### Observed Behavior

The arrow key press would change which menu option was highlighted and also which menu option was chosen

### Reproduction Rate

10-50% (timing based)

### Anything else?

https://user-images.githubusercontent.com/100527514/180854681-27fd1feb-b193-4136-88df-50f8114789ca.mp4
[Player.log](https://github.com/7thbeatgames/rd/files/9184105/Player.log)

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
