### ISSUE TITLE
Disable all Presets option

### ISSUE THREAD

**Issue by wolfplay013** [7thbeatgames/rd#20]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

When you don't want to use an effect anymore which takes up a lot of preset events to disable all of them so maybe a button on the Set VFX Preset that disables all of them.

### Suggestion / Solution

A button that disables all presets

### Alternatives & Workarounds

Using many events to disable each preset seperately.

### Demo & Mockup

![image](https://user-images.githubusercontent.com/60063537/182881293-39197f81-6766-45e8-8556-a90b6ac2ca4e.png)

**Comment by authop** [comment]
This issue has been moved to #24

**Comment by Satellite-7th-Beat-Games** [comment]
Re-opening; although it also concerns the Set VFX Preset level event, this is a separate enough suggestion from #24 to warrant its own issue.
