### ISSUE TITLE
(r25 Beta) Scale has Position Pointer

### ISSUE THREAD

**Issue by wolfplay013** [7thbeatgames/rd#21]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

i can't really explain it but it's pretty unintentional that scaling has a pointer.
![image](https://user-images.githubusercontent.com/60063537/183087774-1893c678-9cd1-415a-b04d-e21255841c85.png)

### Suggestion / Solution

Remove the pointer from scaling

### Demo & Mockup

![image](https://user-images.githubusercontent.com/60063537/183087978-c38eff39-ab6e-4575-8d72-120e95da8629.png)

**Comment by saladplainzone** [comment]
this would have worked better under the bug template i think but the point definitely still stands yeah

**Comment by wolfplay013** [comment]
i may be stupid

**Comment by Satellite-7th-Beat-Games** [comment]
This is only the scale option in the Move Row event, right? If so, fixed in dev

**Comment by wolfplay013** [comment]
yup it is only visible with the scale option
