### ISSUE TITLE
Show full comment on playback

### ISSUE THREAD

**Issue by saladplainzone** [7thbeatgames/rd#22]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

If you have a particularly long comment, and you set it to display during playback, it appears small and truncated, like this, with no way to scroll through them without selecting the event itself:
![image](https://user-images.githubusercontent.com/31338325/183303380-fc5f53b5-694a-4f79-8987-d9082618537a.png)
![image](https://user-images.githubusercontent.com/31338325/183303384-a84f2ac8-4964-4e5b-bd14-eeb144ea7416.png)

### Suggestion / Solution

I suggest that playback comment displays should expand to as large as they can be for the current editor size, showing the full comment if possible.

### Alternatives & Workarounds

You could split something into multiple comments, but this just kind of avoids the issue, especially since the playback preview seems to show _less_ than the regular preview?

### Demo & Mockup

![image](https://user-images.githubusercontent.com/31338325/183303463-087dcd68-a1a3-4205-b9f7-e93d4e00a6ce.png)

### Note

N/A

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
