### ISSUE TITLE
Make old levels that call Logan's "whaat" expression call his new "surprised" expression instead

### ISSUE THREAD

**Issue by willowpoke** [7thbeatgames/rd#23]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Pre-Early Access, Logan's surprised animation was named "whaat", meaning that attempting to play older levels that play that animation now simply have Logan do his neutral animation, rather than do the equivalent, which is the "surprised" animation

### Suggestion / Solution

Make old levels that call Logan's "whaat" expression call his new "surprised" expression instead, much like how Logan will always default to using happySimple, rather than Happy, for his hit animation

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
