### ISSUE TITLE
Set VFX Preset event Cleanup

### ISSUE THREAD

**Issue by Satellite-7th-Beat-Games** [7thbeatgames/rd#24]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

The dropdown list of the "Set VFX Preset" event is getting long, and it feels cluttered with insignificant items, hiding some of the more powerful features that are available through it.

Many of the older effects in it can now be easily created using other Action Tab events or newer customisable presets. For example, the "Row Outline" series of 6 presets can be recreated with the "Paint Rows" event, the 3 "Screen Tile" presets are superseded by "Custom Screen Tile", and the "Custom Screen Scroll" and "VHS" presets can replace the 4 separate combinations of directional screen scroll with/without VHS.

### Suggestion / Solution

We could use the existing mechanism that hides the Miaw Miaw preset from the dropdown for newly created events, and for old events that aren't itself using Miaw Miaw. This should also ensure backwards compatability, keeping older levels from breaking.

### Demo & Mockup

![image](https://user-images.githubusercontent.com/110698441/183808431-ae30d1b7-0461-4806-a809-8ddac9a232ca.png)

**Comment by willowpoke** [comment]
To add to this, some presets could be combined together into one effect with different options, namely the Falling Petal/Confetti effects.

**Comment by authop** [comment]
Mentioning Issue #20 for reference.

**Comment by GDColon** [comment]
I agree with this change, but I've also heard that some people like the row tinting VFX since it's an easier way to apply the effect to all rows in a room rather than having to copy multiple paint events. I suppose the effects can just be surgery'd in but maybe tinting all rows in a room can be moved to the paint rows event.

**Comment by Satellite-7th-Beat-Games** [comment]
> I agree with this change, but I've also heard that some people like the row tinting VFX since it's an easier way to apply the effect to all rows in a room rather than having to copy multiple paint events. I suppose the effects can just be surgery'd in but maybe tinting all rows in a room can be moved to the paint rows event.

Good idea, you can open up a new issue about this! We can probably add it in by enabling the room selector thing when the current "All Rows" option is selected.

**Comment by Satellite-7th-Beat-Games** [comment]
> some people like the row tinting VFX since it's an easier way to apply the effect to all rows in a room rather than having to copy multiple paint events

Room selection for "All Rows" option in "Tint Rows" level event is now done in dev

**Comment by Satellite-7th-Beat-Games** [comment]
Done in dev
![image](https://user-images.githubusercontent.com/110698441/199247664-32d1f7bf-e294-4757-9130-3b62face74a7.png)
