### ISSUE TITLE
Dropdowns are visible in editor fullscreen

### ISSUE THREAD

**Issue by RandomGuyJCI** [7thbeatgames/rd#25]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Random Guy JCI#7029

### Summary

While opening a dropdown, entering fullscreen still shows part of the dropdown and covers part of the level view.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

2. Open any dropdown (this can be the menu dropdown or any dropdown in a level event)
3. Press F to enter fullscreen

### Expected Behavior

The dropdown should automatically be hidden from view.

### Observed Behavior

Part of the dropdown can be seen obstructing the view in fullscreen.

### Reproduction Rate

100%

### Anything else?

Here is an example image of the bug in action:
![image](https://user-images.githubusercontent.com/22722393/183846207-982d4f8c-19da-485b-bfa7-0b8098b78810.png)

**Comment by megaminerjenny** [comment]
Fixed in dev. Closing.
