### ISSUE TITLE
Change Players' Rows does not correctly change when row order changes

### ISSUE THREAD

**Issue by Shareoff** [7thbeatgames/rd#27]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Shareoff#2107

### Summary

Normally, when row order changes, all the corresponding events that refer to the rows (such as Move Row events, Paint Row etc) move with them to keep pointing to the same row. However, Change Players Rows stays on the same index, and as such will affect a different row once row order changes.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows10

### Platform

Steam

### Steps to Reproduce

1. Create two rows with different characters.
2. Create a "Change Players' Rows" event, and set one of the two rows to be CPU using this event.
3. Change the row order by going to the rows tab and reordering one.

### Expected Behavior

I expect the "Change Players' Rows" event to change the index of the row it affects so it continues to affect the same row, so I don't have to manually fix each instance of the event

### Observed Behavior

The "Change Players' Rows" event keeps affecting the same row *index*, which changes which row it affects, so the row that was previously cpu'd is no longer cpu'd and in order to preserve the behaviour I must fix each row manually.

### Reproduction Rate

100%

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
