### ISSUE TITLE
Rhythm Doctor detected as malware on Mac

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/rd#30]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

oliverabola@gmail.com, FlameDance#9223 (won't accept DMs)

### Summary

Upon clicking play in steam, a macOS popup says '"Rhythm Doctor" will damage your computer. You should move it to the Trash.' There is no way to run the game, even after right clicking the application and trying to run.

### Version

Latest non-beta and latest beta (I can't launch game to check)

### Operating System (OS)

macOS Monterey (M1)

### Platform

Steam

### Steps to Reproduce

1. Download game on steam
2. Click play
3. See error

### Expected Behavior

The game would run normally.

### Observed Behavior

MacOS detected the game as malware and prevented from running.

### Reproduction Rate

100%

### Anything else?

The warning that appears when attempting to launch:
<img width="344" alt="Screen Shot 2022-09-04 at 6 10 25 PM" src="https://user-images.githubusercontent.com/100527514/188341899-66b41c75-9e7c-4d9c-a640-831f557e6598.png">

**Comment by DPS2004** [comment]
this bug should have been fixed i think, but try doing this:
https://www.notion.so/RD-Technical-Problems-FAQ-fe2aec8dc5f24446ae079d135d7b81d6#9aff0fd925a6417e8402af70b65e4936

**Comment by Non-Binary-Programmer** [comment]
That worked, thanks!
