### ISSUE TITLE
Running tags don't differentiate audio events leading to a delay with high visual offset

### ISSUE THREAD

**Issue by RandomGuyJCI** [7thbeatgames/rd#32]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Random Guy JCI#7029

### Summary

When running tags, it takes into account the visual offset from your settings. Although this is needed for visual events, audio events run without visual offset which gives tagged audio events a noticeable amount of delay when run. The higher your visual offset is, the greater the delay.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. In the editor, create a few Set Sound events that run in a regular interval
2. Tag the last Set Sound
3. Run the tag on the beat of the last Set Sound
4. Set your visual offset to something high like 1000 ms
5. Play the level
6. Set your visual offset to 0 ms
7. Play the level again

### Expected Behavior

The tagged set sound event should always align with the rhythm of the other set sound events.

### Observed Behavior

Running the level with 0 ms offset makes the sound align with the others, while running the level with 1000 ms offset delays the sound by 1 second.

### Reproduction Rate

100%

### Anything else?

Here's an example video of the issue:

https://user-images.githubusercontent.com/22722393/188523322-1d1a49a3-9682-41bd-8914-6a47786b0bff.mp4

**Comment by megaminerjenny** [comment]
Fixed in dev (finally. that was painful). closing.
https://user-images.githubusercontent.com/40370440/227804132-58c19516-9c13-40ca-83cd-83708b4552e5.mp4
