### ISSUE TITLE
Deleting the last conditional keeps the conditional buttons (wrench, copy, delete) there, leading to errors

### ISSUE THREAD

**Issue by 9thCore** [7thbeatgames/rd#35]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

9thCore#5404

### Summary

Deleting the last conditional using the Shift delete feature in the conditional selector seems to cause the wrench, copy and delete buttons to remain, causing errors if clicked.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Create a few conditionals (any type).
2. Hold Shift and delete the last one in the conditional selector.
3. Bug! The wrench, copy and delete buttons remain there even though there is no longer a conditional.
4. Hover over any of the other conditionals and they go away.

### Expected Behavior

The buttons would disappear when the conditional is deleted, as there isn't a conditional there anymore.

### Observed Behavior

They remain, leading to errors such as `ArgumentOutOfRangeException` and `NullReferenceException`, as well as buggy behaviour when trying to change the conditional's name, expression and type.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/rd/files/9545013/Player.log)
[Video](https://streamable.com/eufphr)

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
