### ISSUE TITLE
Discarding a hold beat's free time pulse causes freezing the level

### ISSUE THREAD

**Issue by CooMonkey** [7thbeatgames/rd#45]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

(Discord) CooMonkey#0378

### Summary

If you select discarding the pulse in pulse action when there's a pulse having hold time, the level get frozen.

### Version

v0.11.5 (r25)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Break a classic beat into free time pulses
2. Set hold time on any of them and place a discard event
3. Play the preview

### Expected Behavior

Normally perform discarding the pulse like the one having no hold time

### Observed Behavior

Next bar's events cannot be loaded and then the level freezes

### Reproduction Rate

100%

### Anything else?

https://user-images.githubusercontent.com/114681726/193102130-a2c0def1-9a83-471b-a40c-7c7cb48bbd2c.mp4

[Player.log](https://github.com/7thbeatgames/rd/files/9677755/Player.log)

**Comment by megaminerjenny** [comment]
Fixed in dev. Closing.
