### ISSUE TITLE
Level editor: Add user customizable palette to color picker

### ISSUE THREAD

**Issue by Satellite-7th-Beat-Games** [7thbeatgames/rd#46]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Trying to keep colors consistent throughout a level when using row tints and flashes etc. is difficult.

It is also a hassle to change your mind about color usage midway through the level, you would need to either change all the affected events one by one, or use surgery and do a find-and-replace on text.

### Suggestion / Solution

Add a palette to the color picker window, letting users quickly select custom defined colors. Events that use palette colors will point to an index in the palette instead of using a color code, so the event's color will be updated when the palette is modified.

The palette would be saved into the .rdlevel file, so it can persist through editor sessions, and so levels know what actual colors the palette indices refer to during gameplay.

### Alternatives & Workarounds

An alternative would be keeping color hex codes in a separate text file, then copy pasting them into the color picker window when needed.

### Demo & Mockup

Using the MSPaint palette colors as an example:

![palette mockup](https://user-images.githubusercontent.com/110698441/193159342-3cc0b5d8-33be-4980-9875-c498e6d047a1.png)

In this example, the event will use the highlighted palette color. With a palette slot selected, changing the color using the controls will change the palette, affecting all events that refer to that palette index. 

Clicking on the highlighted palette slot again deselects it, making the event keep the current color, but not linking this event to the palette in case of future updates. All old levels will default to this behavior to maintain backwards compatability.

**Comment by megaminerjenny** [comment]
Added this in dev!
