### ISSUE TITLE
Add Opacity to "Paint Hands"

### ISSUE THREAD

**Issue by purplpasta** [7thbeatgames/rd#50]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

"Paint Rows" has an option to set the opacity of the whole row, however "Paint Hands" does not. For consistency (and for an effect I want to create) it would be nice to have the opacity option for both.

### Suggestion / Solution

Add an "Opacity" slider to the "Paint Hands" event, similar to the one in "Paint Rows"

**Comment by megaminerjenny** [comment]
Implemented in dev!
