### ISSUE TITLE
Level progression sequence sets next level progress to Unplayed, even if level already has a rank

### ISSUE THREAD

**Issue by Satellite-7th-Beat-Games** [7thbeatgames/rd#54]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

Level progression events and cutscenes incorrectly assume the next level in sequence is in the "Locked" state and sets it to "Unplayed".

This can end up resetting the rank of levels the player already has progress in, for instance when save files are bugged or corrupted, or when the level sequence is adjusted by inserting or moving around levels.

### Version

all

### Operating System (OS)

all

### Platform

all

### Steps to Reproduce

1. In a new save file, set levels 1-1 and 1-2 to passed.
2. Set 1-1 to "unplayed" then pass it again, triggering the level complete cutscene.
3. After the cutscene in the level select screen, 1-2 will be to "Unplayed" again too.

### Expected Behavior

Implement fix: check if next level in sequence is actually "Locked" and doesn't already have a rank, before "unlocking" the level and setting its rank to Unplayed.

### Observed Behavior

see summary

**Comment by RandomGuyJCI** [comment]
Solved, closing issue!
