### ISSUE TITLE
Change the window name to display the “All The Times” lyrics

### ISSUE THREAD

**Issue by ColdlordXRepositories** [7thbeatgames/rd#56]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

There isn’t a problem I just think it would fit in with the mechanic

### Suggestion / Solution

Basically, in all the times, the window moves. However, the song doesn’t have lyrics yet, so I propose the window title changes to display the lyrics! It’s a fun way to have lyrics for people who need them, and it also fits in with the window dance mechanic.
If possible, this should also be an event in the editor.

### Alternatives & Workarounds

It’s literally impossible like there are no functions coded in to let this happen

### Demo & Mockup

![8933A7DA-46D8-4096-92E1-1C0E124C061B](https://user-images.githubusercontent.com/49921877/202866031-5e6807eb-f8b4-4893-8279-9fa95e213a23.png)

### Note

The lyrics might be hard to see in some parts of songs.

**Comment by R3Ked** [comment]
that would be really funny but also kinda unnecessary

**Comment by ColdlordXRepositories** [comment]
> that would be really funny but also kinda unnecessary

Is it unnecessary? Yes. But would it fit in with the song, especially since it doesn't have lyrics yet? Yes.

**Comment by authop** [comment]
As it is mainly the OS side, we cannot guarantee that it will work on all supported platforms (Windows, macOS, Linux). It will likely be OS-specific.
While we do not pursue such gimmicks, I'll ask around to see if it is doable.
