### ISSUE TITLE
Simultaneous beats discarded when p1/p2 offsets are slightly different on 2p/nurse-assisted (Intimate, Both Distant Duets, etc) levels 

### ISSUE THREAD

**Issue by minerharry** [7thbeatgames/rd#57]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

miner.harry567@gmail.com

### Summary

In level scenes where Ian/Paige have their own hand pressing a button (midway through 1-2, beginning of both 3-3 and 3-3N, and maybe others I haven't thought to test), it seems that when their patient and mine have simultaneous beats, having slightly different player one and player two input offsets just breaks my ability to hit the beat (in 1p). If I hit it on time, a blue flash appears, but the yellow heart trace does not show up and the heart cracks a second later. If I don't hit at all, the heart cracks as normal (e.g. Paige's hand does not hit the beat). If I'm early/late, the heart cracks as normal and the trace appears. When the p1/p2 inputs are synced, this works as normal.

With very close input values (119ms and 109ms), this was very consistent. I think there is a window with larger differences (I occasionally got some with 119 and 79; not sure if the failures there were because different beats have different rules or if I just suck) but if so it's definitely smaller than with equal inputs.

I've been going back through the game to S+ the levels and recently ran into this, not remembering it happening before; I realized while writing this report that I had been manually adjusting input offsets using the millisecond offset display instead of doing calibration, which ended up being the problem. This was incredibly confusing when I first encountered it!

### Version

v0.12.0 (r27)

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

Lenovo Thinkpad

### Steps to Reproduce

1. Set p1 and p2 input offsets to slightly different values (for me, p1 119 and p2 109 was very consistent)
2. Start level 3-3
3. attempt to hit the first cue from mrs. stevenson
4. cry

### Expected Behavior

Heart should be hit correctly

### Observed Behavior

Impossible to hit the cue - early/late/miss all fail as normal, but hitting on time flashes blue w/ no heart trace and fails anyway.

### Reproduction Rate

100% with 119 vs 109, ~50% with 119 and 79

**Comment by Satellite-7th-Beat-Games** [comment]
fixed by morph in dev
