### ISSUE TITLE
Have the row reflections in 3-1 jump instead of slide

### ISSUE THREAD

**Issue by purplpasta** [7thbeatgames/rd#59]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

The bird sliding around during the dancing part looked unnatural, so I'd suggest to have the reflections jump (except for Logan and Hailey's movement to and from the dance)

### Suggestion / Solution

rowReflectionsJumping = true

**Comment by megaminerjenny** [comment]
Done! Looks like Hailey forgot to hop at the end too, so she now remembers to do that also.
