### ISSUE TITLE
Opening the F1 menu while full screened in the editor won't let you press buttons.

### ISSUE THREAD

**Issue by purplpasta** [7thbeatgames/rd#60]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

purplpasta#9136

### Summary

While in the editor, pressing F1 brings up a "Welcome to the Rhythm Doctor Editor..." menu. If you have the level preview in full screen, the "Agree" and "Return" buttons can't be clicked until you press Escape to return to the normal editor view.

### Version

v0.12.0 (r27)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Open the Editor
2. Press [F] or the full screen button to set the preview to fullscreen mode
3. Press the [F1]
4. Try to click on Agree or Return

### Expected Behavior

Buttons are clickable, even if the preview is in full screen

### Observed Behavior

Buttons are not clickable in full screen

### Reproduction Rate

100%

**Comment by megaminerjenny** [comment]
Fixed in dev - the copyright popup can no longer be active at the same time as fullscreen, preventing this situation from occurring. Should be good to close unless you really really need to be able to pull up that popup in fullscreen for some reason.
