### ISSUE TITLE
Game crashes when opening too many new levels

### ISSUE THREAD

**Issue by Juandif** [7thbeatgames/rd#62]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Juandif#2563

### Summary

When opening a lot of new levels in the CLS the game freezes then crashes, as for how many levels are needed for it to crash i don't really know the exact amount but i'd say about a third or fourth of my entire cls' levels so about 200~300 in my case.

### Version

v0.12.0 (r27)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Go into the CLS 
2. Open a ton of levels (like i said before about 200~300 should work)
3. Game crashes

### Expected Behavior

I expected the game to still run after opening a shitton of levels.

### Observed Behavior

It crashed after opening a shitton of levels.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/rd/files/10197104/Player.log)
Here is the log file.

**Comment by authop** [comment]
It is one of the extreme conditions that devs do not presume at all. Why would you need to open 300+ levels? The log file doesn't have relevant info too.
I'm closing this as not planned, but you are welcome to give us the log file containing the moment of the crash.
