### ISSUE TITLE
Set Crotchets Per Bar not shrinking correctly when the events view is collapsed

### ISSUE THREAD

**Issue by R3Ked** [7thbeatgames/rd#69]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

R3Ked#7092

### Summary

I collapsed the events view and yeah
![image](https://user-images.githubusercontent.com/20342336/210678616-cba44b42-01b5-4e33-8f01-060503638cd5.png)

### Version

v0.12.1 (r28)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Place Set Crotchets Per Bar
2. Press the button to shrink down the events to half of their size
3. See this happen

### Expected Behavior

The event shrinks like it should

### Observed Behavior

The numerator doesn't shrink right leading to a funny visual glitch

### Anything else?

This is minor but funny

**Comment by R3Ked** [comment]
i just realized this is issue 69 damn this is kinda lame

**Comment by megaminerjenny** [comment]
Fixed in dev. Unity text scaling my beloathed.
