### ISSUE TITLE
Level 1-CNY Counts Mistakes Incorrectly

### ISSUE THREAD

**Issue by person2400** [7thbeatgames/rd#73]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

@Person#7606

### Summary

When playing level 1-CNY, "Chinese New Year", mistakes made throughout the song do not count against the player, making it possible to get an S rank with 0 mistakes, even after making several mistakes.

### Version

v0.12.0 (r27)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Enter level 1-CNY.
2. Miss every input, except for the last four.
3. The game will give the player an S rank, saying that they made 0 mistakes. Note that missing all inputs gives the player a B rank, saying the player made 6 mistakes.

### Expected Behavior

The game should give a lower ranking, due to the missed inputs. The game should also show a larger number of mistakes.

### Observed Behavior

The player is given an S or S+ rank.

### Reproduction Rate

100%

### Anything else?

See link. Video shows three playthroughs. First playthrough only hits final four inputs (player gets an S). Second misses all inputs (player gets a B, with 6 mistakes). Third hits all inputs except for the last four (player gets a B, with 6 mistakes).

[https://www.youtube.com/watch?v=Rw_AYtnYAV4](url)

**Comment by huantianad** [comment]
Fixed in dev!
