### ISSUE TITLE
Custom character (CC) speech blip files aren't loaded to audio clip library if the CC is referenced in dialogue events only

### ISSUE THREAD

**Issue by Satellite-7th-Beat-Games** [7thbeatgames/rd#74]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

https://discord.com/channels/296802696243970049/304720987319173121/1080410275477454918

> is smth wrong with this blip? I have it in the folder with the CC but it's not playing in-game
it has the exact same name as the CC as well
it's also 0.05 seconds long so it's short enough to be recognized
but the game still uses the default blip
oh nvm it
it only works when there's a row with the CC???

> or when it's custom play sound of the same name is present.
this is likely a bug...

> Satellite — Today at 19:47
ah whoops
i think the code only loads the speech blip file when a cc with the same name has a row, or if it's explicity referenced like other audio files. so using a cc in dialogue only doesn't load the file, and won't include the file into the rdzip when publishing. may fix somewhere down the line. or not, because i don't know how to scan every dialogue event in the level for a list of characters and expressions used then attempt to load possible audio files

### Version

all

### Operating System (OS)

all

### Platform

all

### Steps to Reproduce

1. Add dialogue event to level, using a CC that has valid speech blip files in same directory as level file
2. DO NOT create a row for the CC, or load the speech blip with a Play Sound event
3. Run level

### Expected Behavior

Dialogue uses included custom CC speech blip

### Observed Behavior

Dialogue instead uses fallback pop sound for CC speech

**Comment by RandomGuyJCI** [comment]
Fixed in dev!
