### ISSUE TITLE
Background Not Loading Unless Editor Opened

### ISSUE THREAD

**Issue by TheXinventor** [7thbeatgames/rd#76]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

TheXinventor#0926

### Summary

When playing [this level](https://github.com/7thbeatgames/rd/files/11026463/Level.zip) from the custom levels library, the room 3 background doesn't appear. If the level editor is opened (not necessarily on this level) and then the level is played from the library, the background now appears. This behaviour resets upon quitting the game.

### Version

r28

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Open 'Custom Levels' menu
2. Import rdzip
3. Select level and play
4. Finish or quit out of level
5. Open level editor (via main menu or 'edit' option on level)
6. Close level editor
7. Select level and play again

### Expected Behavior

Room 3 background has diamond pattern both times level is opened

### Observed Behavior

Room 3 background is black on first playthrough, then has intended pattern on the second

### Reproduction Rate

100%

### Anything else?

Through testing, I have confirmed this is NOT due to:
- Overlapping rooms
- Setting background colour and image on the same beat (in room 2)
- Setting background on the first beat
- The 'blur' vfx preset

[Here](https://github.com/7thbeatgames/rd/files/11026524/Player.log) is the log upon testing this bug and quitting

**Comment by huantianad** [comment]
Good catch, thanks for the bug report. Fixed in dev
