### ISSUE TITLE
[Editor] Save Prompt in Fullscreen Level Preview makes Editor completely lock up

### ISSUE THREAD

**Issue by saladplainzone** [7thbeatgames/rd#77]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

saladplainzone#1925

### Summary

When editing a level, if you have the level preview fullscreened, have unsaved changes, and try to close the game, the unsaved changes popup will appear, but since you're in fullscreen it won't allow you to interact with it, nor will it let you do anything with any key, locking you there.

### Version

v0.13.1 (r29) [Beta Branch]

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

GPU: RTX 3060
CPU: Ryzen 7 5800h
RAM: 16 GB

### Steps to Reproduce

1. Start a level in the editor
2. Make a change
3. Fullscreen the level preview
4. Try to close the game window

### Expected Behavior

Unsaved changes dialog should be interactable or dismissable somehow, maybe ideally just enabling mouse interactivity when it's there.

### Observed Behavior

Game completely locks up, preventing both closing the game or saving the level, and will only accept being force-closed through task manager.

### Reproduction Rate

100%

### Anything else?

https://user-images.githubusercontent.com/31338325/229259464-959a9853-10f3-4b3e-b7ec-63ff0dddbea0.mp4

Nothing in the log seemed to indicate a failure in the game running, I think this is mainly just a weird quirk of how some bits of the editor interact with eachother.

**Comment by megaminerjenny** [comment]
Fixed in dev. Closing.
