### ISSUE TITLE
Camera gets stuck if a level is selected while it is still scrolling

### ISSUE THREAD

**Issue by willowpoke** [7thbeatgames/rd#8]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

willowpoke#0492

### Summary

When selecting a level in the story mode level select when the camera is still scrolling, the camera gets stuck in the position it was in when you selected the level, until you make it move again.

### Version

v0.11.6 (r26)

### Operating System (OS)

Windows 11

### Platform

Steam

### Steps to Reproduce

1. Make the camera scroll a significant distance, the easiest way to do this is to have the cursor warp from the Art Room over to One Shift More
2. Select a level while the camera is still scrolling

### Expected Behavior

The camera stays focused on the level you selected

### Observed Behavior

The camera gets stuck at wherever it last was before selecting the level when you deselect it

### Reproduction Rate

100%

### Anything else?

https://cdn.discordapp.com/attachments/943590199772991561/1002007717579345920/Rhythm_Doctor_HEh5QqKmWj.gif

**Comment by megaminerjenny** [comment]
Fixed in dev. Closing.
