### ISSUE TITLE
Floating Text - ignore one '/' if its the last character of a line

### ISSUE THREAD

**Issue by fizzd** [7thbeatgames/rd#80]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

FLOATING TEXT - can we automatically ignore one '/' if its the last character of a line? It looks 'normal' to have a / at the end of every syllable so im always caught out by the fact that you need to not have one at the end of the line

Maybe some people have used extra /s as a hack to prolong the lyric but thats fine to break backward compat for such a small thing imo.

### Suggestion / Solution

-

**Comment by megaminerjenny** [comment]
Implemented in dev! Closing.
