### ISSUE TITLE
VFX Filter by Room buttons

### ISSUE THREAD

**Issue by fizzd** [7thbeatgames/rd#81]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

When doing multiple room's VFX, often i want to work on each rooms vfx separately because they are totally different things happening in each one. I wish VFX had 'filter by room 1/2/3/4' buttons on the left side, in addition to the filter by conditions that already exists.

### Suggestion / Solution

-

**Comment by megaminerjenny** [comment]
Done in dev! Closing.
