### ISSUE TITLE
Palettes - show which ones are in use

### ISSUE THREAD

**Issue by fizzd** [7thbeatgames/rd#82]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

PALETTES - super cool! but its easy for me to forget which ones im using (since they are all already different colors). Would be cool to be able to show which ones are in use by an event, maybe with a mark on the color, or having the border of that color, be a different color?

### Suggestion / Solution

-

**Comment by megaminerjenny** [comment]
Implemented in dev! Closing.

**Comment by megaminerjenny** [comment]
Juuuuuust realized I read this wrong and implemented something different heh. I'm sure what I did is still useful but I get what you mean now. Re-opening.
