### ISSUE TITLE
Metronome doesn't make noise when there is silence in the level

### ISSUE THREAD

**Issue by dylanr3** [7thbeatgames/rd#88]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

@dndryan discord

### Summary

The metronome doesn't play any sound when there is no sound in the level or song, neither does playing the metronome sounds through the Play Sound event. changing the sound type doesn't fix it

### Version

game v0.13.1 (r29), editor r27

### Operating System (OS)

Windows

### Platform

Steam

### Device Info

Laptop

### Steps to Reproduce

1. create a play song event and play a song with either gaps of no audio, or no audio at all
2. turn on metronome
OR 2. play metronome sounds through Play Sound
3. get no audio

### Expected Behavior

it plays the metronome sounds fine

### Observed Behavior

metronome blips in occasionally but it generally silent

### Reproduction Rate

95%

**Comment by Satellite-7th-Beat-Games** [comment]
cannot reproduce. this sounds like an issue with your own devices, particularly if bluetooth is involved. the metronome blip is very short (like 60 milliseconds long), and some devices have a sort of "activation" threshold that requires continuous sound to be played to wake them from silence.
check if this also happens with super short sound files outside of the game.
