### ISSUE TITLE
Early hits cause triangleshots to be stuck on svt row

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/rd#9]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

oliverabola@gmail.com, FlameDance#9223 (won't accept DMs)

### Summary

If you hit both hits of a triangleshot before either should be hit, one of the triangleshots will get graphically stuck at the start of its svt row until you hit/miss another set of triangleshots without performing the glitch.

### Version

v0.11.6

### Operating System (OS)

Windows 11

### Platform

Steam

### Device Info

PC

### Steps to Reproduce

1. Enter a level with triangleshots (two oneshots on an svt row in quick succession that are visually shaped like triangles), such as MD-1 or MD-3
2. Play normally until a triangleshot is cued (with the voiceline of "two!")
3. Quickly hit two or more keys as soon as both triangleshots appear on the svt row

Alternative reproduction steps:

1. Same as above
2. Mash buttons for the entire level
3. See error

This is easier, but less consistent.

### Expected Behavior

Both triangleshots would disappear from the svt row.

### Observed Behavior

One triangleshot would remain on the svt row.

### Reproduction Rate

75-90% (timing based)

### Anything else?

[Player.log](https://github.com/7thbeatgames/rd/files/9215083/Player.log)
After performing the glitch, svt cues will overlap with the glitched triangleshot:
![image](https://user-images.githubusercontent.com/100527514/181660186-2e0977c8-7e31-4d57-9a85-71e3bd62a152.png)
[Reproduction video](https://user-images.githubusercontent.com/100527514/181660390-c70e561f-0ae3-494d-879e-0e3c0096133f.mp4)

**Comment by Satellite-7th-Beat-Games** [comment]
i think jenny fixed this in dev
